/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_spore_jni_ImageUtilEngine */

#ifndef _Included_com_spore_jni_ImageUtilEngine
#define _Included_com_spore_jni_ImageUtilEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_isvsa_jni_ImageUtilEngine
 * Method:    decodeYUV420SP
 * Signature: ([BII)[I
 */
JNIEXPORT jintArray JNICALL Java_com_isvsa_jni_ImageUtilEngine_decodeYUV420SP
  (JNIEnv *, jobject, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
